title: Frosty Tool Suite Research & Summaries
description: Open-Source Research & AI-Generated Summaries for the Frosty Tool Suite. Developer purposes.

theme: minima
baseurl: /FrostyToolSuite-Research-Notes
github_username: 8bllgrl

exclude:
  - README.md
  - .gitignore